services:
  frontend: 
    build:
      context: ./front-end # directory to find the thing
      dockerfile: Dockerfile
    ports: 
      - "9000" # container 9000
    depends_on:
      - backend

  backend:
    build:
      context: ./back-end # directory to find the thing
      dockerfile: Dockerfile
    ports: 
      - "5252" # container 5252
  
  proxy:
    build:
      context: ./proxy # directory to find the thing
      dockerfile: Dockerfile # file within the proxy directory
    ports:
    - "80:80" # host 80 -> container 80
    depends_on:
    - frontend
    - backend
